import { uuidv7 } from "uuidv7";

/**
 * Entity prefix constants for all Emito-owned IDs.
 * `emito_subscribers.id` is the exception — host app's user ID, not generated by Emito.
 */
export const ID_PREFIX = Object.freeze({
	notification: "ntf",
	preference: "pref",
	workspaceDefault: "wsd",
	category: "cat",
	topic: "top",
	topicSubscription: "tsc",
	list: "lst",
	listMember: "lmb",
	inbox: "inb",
	webhookEndpoint: "whe",
	webhookDelivery: "whd",
	pushToken: "ptk",
	integration: "int",
	consent: "con",
	suppression: "sup",
	deadLetter: "dlq",
	erasureLog: "erl",
	audit: "aud",
	alert: "alr",
	alertHistory: "ahi",
	savedView: "sav",
	apiKey: "apk",
	scheduledSend: "sch",
	broadcast: "brc",
	templateOverride: "tmo",
	teamMember: "mbr",
} as const);

/**
 * Generate a prefixed UUID v7 ID.
 * Returns `{prefix}_{uuidv7}` with dashes stripped from the UUID.
 *
 * @example
 * generateId('ntf') // 'ntf_0192e4a2b6c8d0e1f2a3b4c5d6e7f8a9'
 */
export function generateId(prefix: string): string {
	const uuid = uuidv7().replace(/-/g, "");
	return `${prefix}_${uuid}`;
}
