export const EMITO_ERROR_CODE = Object.freeze({
	CONFIG_INVALID: "CONFIG_INVALID",
	CONFIG_MISSING_PROVIDER: "CONFIG_MISSING_PROVIDER",
	SUBSCRIBER_NOT_FOUND: "SUBSCRIBER_NOT_FOUND",
	SUBSCRIBER_ERASED: "SUBSCRIBER_ERASED",
	CONSENT_REQUIRED: "CONSENT_REQUIRED",
	CATEGORY_BLOCKED: "CATEGORY_BLOCKED",
	PREFERENCE_NOT_FOUND: "PREFERENCE_NOT_FOUND",
	PREFERENCE_BLOCKED: "PREFERENCE_BLOCKED",
	DELIVERY_FAILED: "DELIVERY_FAILED",
	DELIVERY_REJECTED: "DELIVERY_REJECTED",
	DELIVERY_HARD_BOUNCE: "DELIVERY_HARD_BOUNCE",
	DELIVERY_INVALID_ADDRESS: "DELIVERY_INVALID_ADDRESS",
	DELIVERY_SPAM_COMPLAINT: "DELIVERY_SPAM_COMPLAINT",
	DELIVERY_SOFT_BOUNCE: "DELIVERY_SOFT_BOUNCE",
	ALL_PROVIDERS_EXHAUSTED: "ALL_PROVIDERS_EXHAUSTED",
	RATE_LIMITED: "RATE_LIMITED",
	PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
	PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
	CIRCUIT_BREAKER_OPEN: "CIRCUIT_BREAKER_OPEN",
	TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
	TEMPLATE_RENDER_FAILED: "TEMPLATE_RENDER_FAILED",
	WEBHOOK_SIGNING_FAILED: "WEBHOOK_SIGNING_FAILED",
	WEBHOOK_ENDPOINT_DISABLED: "WEBHOOK_ENDPOINT_DISABLED",
	WEBHOOK_DELIVERY_FAILED: "WEBHOOK_DELIVERY_FAILED",
	WEBHOOK_SIGNATURE_INVALID: "WEBHOOK_SIGNATURE_INVALID",
	WEBHOOK_PARSE_FAILED: "WEBHOOK_PARSE_FAILED",
	WEBHOOK_PROVIDER_NOT_FOUND: "WEBHOOK_PROVIDER_NOT_FOUND",
	DIGEST_FLUSH_FAILED: "DIGEST_FLUSH_FAILED",
	TRANSPORT_CONNECTION_FAILED: "TRANSPORT_CONNECTION_FAILED",
	TRANSPORT_DISCONNECTED: "TRANSPORT_DISCONNECTED",
	SUPPRESSED_ADDRESS: "SUPPRESSED_ADDRESS",
	ERASURE_FAILED: "ERASURE_FAILED",
	AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
	AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
	AUTH_INSUFFICIENT_ROLE: "AUTH_INSUFFICIENT_ROLE",
	AUTH_INVALID_API_KEY: "AUTH_INVALID_API_KEY",
	CURSOR_INVALID: "CURSOR_INVALID",
	ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
	DEAD_LETTER_NOT_FOUND: "DEAD_LETTER_NOT_FOUND",
	SUPPRESSION_NOT_FOUND: "SUPPRESSION_NOT_FOUND",
	INTEGRATION_NOT_FOUND: "INTEGRATION_NOT_FOUND",
	INBOX_NOT_FOUND: "INBOX_NOT_FOUND",
	RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
	RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
	REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
	PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	INTERNAL_ERROR: "INTERNAL_ERROR",
} as const);

export type EmitoErrorCode = (typeof EMITO_ERROR_CODE)[keyof typeof EMITO_ERROR_CODE];

export type ErrorClassification = "permanent" | "transient" | "rate_limited" | "soft_bounce";

const ERROR_STATUS_CODES: Readonly<Record<EmitoErrorCode, number>> = Object.freeze({
	CONFIG_INVALID: 500,
	CONFIG_MISSING_PROVIDER: 500,
	SUBSCRIBER_NOT_FOUND: 404,
	SUBSCRIBER_ERASED: 410,
	CONSENT_REQUIRED: 403,
	CATEGORY_BLOCKED: 403,
	PREFERENCE_NOT_FOUND: 404,
	PREFERENCE_BLOCKED: 403,
	DELIVERY_FAILED: 502,
	DELIVERY_REJECTED: 502,
	DELIVERY_HARD_BOUNCE: 502,
	DELIVERY_INVALID_ADDRESS: 502,
	DELIVERY_SPAM_COMPLAINT: 502,
	DELIVERY_SOFT_BOUNCE: 502,
	ALL_PROVIDERS_EXHAUSTED: 503,
	RATE_LIMITED: 429,
	PROVIDER_UNAVAILABLE: 503,
	PROVIDER_TIMEOUT: 504,
	CIRCUIT_BREAKER_OPEN: 503,
	TEMPLATE_NOT_FOUND: 404,
	TEMPLATE_RENDER_FAILED: 500,
	WEBHOOK_SIGNING_FAILED: 500,
	WEBHOOK_ENDPOINT_DISABLED: 422,
	WEBHOOK_DELIVERY_FAILED: 502,
	WEBHOOK_SIGNATURE_INVALID: 401,
	WEBHOOK_PARSE_FAILED: 400,
	WEBHOOK_PROVIDER_NOT_FOUND: 404,
	DIGEST_FLUSH_FAILED: 500,
	TRANSPORT_CONNECTION_FAILED: 503,
	TRANSPORT_DISCONNECTED: 503,
	SUPPRESSED_ADDRESS: 422,
	ERASURE_FAILED: 500,
	AUTH_INVALID_TOKEN: 401,
	AUTH_MISSING_TOKEN: 401,
	AUTH_INSUFFICIENT_ROLE: 403,
	AUTH_INVALID_API_KEY: 401,
	CURSOR_INVALID: 400,
	ROUTE_NOT_FOUND: 404,
	DEAD_LETTER_NOT_FOUND: 404,
	SUPPRESSION_NOT_FOUND: 404,
	INTEGRATION_NOT_FOUND: 404,
	INBOX_NOT_FOUND: 404,
	RESOURCE_NOT_FOUND: 404,
	RESOURCE_CONFLICT: 409,
	REQUEST_TIMEOUT: 408,
	PAYLOAD_TOO_LARGE: 413,
	VALIDATION_ERROR: 400,
	INTERNAL_ERROR: 500,
});

export const RETRYABLE_RECORD: Readonly<Record<EmitoErrorCode, boolean>> = Object.freeze({
	CONFIG_INVALID: false,
	CONFIG_MISSING_PROVIDER: false,
	SUBSCRIBER_NOT_FOUND: false,
	SUBSCRIBER_ERASED: false,
	CONSENT_REQUIRED: false,
	CATEGORY_BLOCKED: false,
	PREFERENCE_NOT_FOUND: false,
	PREFERENCE_BLOCKED: false,
	DELIVERY_FAILED: true,
	DELIVERY_REJECTED: false,
	DELIVERY_HARD_BOUNCE: false,
	DELIVERY_INVALID_ADDRESS: false,
	DELIVERY_SPAM_COMPLAINT: false,
	DELIVERY_SOFT_BOUNCE: true,
	ALL_PROVIDERS_EXHAUSTED: false,
	RATE_LIMITED: true,
	PROVIDER_UNAVAILABLE: true,
	PROVIDER_TIMEOUT: true,
	CIRCUIT_BREAKER_OPEN: true,
	TEMPLATE_NOT_FOUND: false,
	TEMPLATE_RENDER_FAILED: false,
	WEBHOOK_SIGNING_FAILED: false,
	WEBHOOK_ENDPOINT_DISABLED: false,
	WEBHOOK_DELIVERY_FAILED: true,
	WEBHOOK_SIGNATURE_INVALID: false,
	WEBHOOK_PARSE_FAILED: false,
	WEBHOOK_PROVIDER_NOT_FOUND: false,
	DIGEST_FLUSH_FAILED: true,
	TRANSPORT_CONNECTION_FAILED: true,
	TRANSPORT_DISCONNECTED: true,
	SUPPRESSED_ADDRESS: false,
	ERASURE_FAILED: true,
	AUTH_INVALID_TOKEN: false,
	AUTH_MISSING_TOKEN: false,
	AUTH_INSUFFICIENT_ROLE: false,
	AUTH_INVALID_API_KEY: false,
	CURSOR_INVALID: false,
	ROUTE_NOT_FOUND: false,
	DEAD_LETTER_NOT_FOUND: false,
	SUPPRESSION_NOT_FOUND: false,
	INTEGRATION_NOT_FOUND: false,
	INBOX_NOT_FOUND: false,
	RESOURCE_NOT_FOUND: false,
	RESOURCE_CONFLICT: false,
	REQUEST_TIMEOUT: true,
	PAYLOAD_TOO_LARGE: false,
	VALIDATION_ERROR: false,
	INTERNAL_ERROR: false,
});

export const RETRYABLE_CODES: ReadonlySet<EmitoErrorCode> = new Set(
	(Object.entries(RETRYABLE_RECORD) as [EmitoErrorCode, boolean][])
		.filter(([, v]) => v)
		.map(([k]) => k),
);

export const SUPPRESSABLE_RECORD: Readonly<Record<EmitoErrorCode, boolean>> = Object.freeze({
	CONFIG_INVALID: false,
	CONFIG_MISSING_PROVIDER: false,
	SUBSCRIBER_NOT_FOUND: false,
	SUBSCRIBER_ERASED: false,
	CONSENT_REQUIRED: false,
	CATEGORY_BLOCKED: false,
	PREFERENCE_NOT_FOUND: false,
	PREFERENCE_BLOCKED: false,
	DELIVERY_FAILED: false,
	DELIVERY_REJECTED: false,
	DELIVERY_HARD_BOUNCE: true,
	DELIVERY_INVALID_ADDRESS: true,
	DELIVERY_SPAM_COMPLAINT: true,
	DELIVERY_SOFT_BOUNCE: false,
	ALL_PROVIDERS_EXHAUSTED: false,
	RATE_LIMITED: false,
	PROVIDER_UNAVAILABLE: false,
	PROVIDER_TIMEOUT: false,
	CIRCUIT_BREAKER_OPEN: false,
	TEMPLATE_NOT_FOUND: false,
	TEMPLATE_RENDER_FAILED: false,
	WEBHOOK_SIGNING_FAILED: false,
	WEBHOOK_ENDPOINT_DISABLED: false,
	WEBHOOK_DELIVERY_FAILED: false,
	WEBHOOK_SIGNATURE_INVALID: false,
	WEBHOOK_PARSE_FAILED: false,
	WEBHOOK_PROVIDER_NOT_FOUND: false,
	DIGEST_FLUSH_FAILED: false,
	TRANSPORT_CONNECTION_FAILED: false,
	TRANSPORT_DISCONNECTED: false,
	SUPPRESSED_ADDRESS: false,
	ERASURE_FAILED: false,
	AUTH_INVALID_TOKEN: false,
	AUTH_MISSING_TOKEN: false,
	AUTH_INSUFFICIENT_ROLE: false,
	AUTH_INVALID_API_KEY: false,
	CURSOR_INVALID: false,
	ROUTE_NOT_FOUND: false,
	DEAD_LETTER_NOT_FOUND: false,
	SUPPRESSION_NOT_FOUND: false,
	INTEGRATION_NOT_FOUND: false,
	INBOX_NOT_FOUND: false,
	RESOURCE_NOT_FOUND: false,
	RESOURCE_CONFLICT: false,
	REQUEST_TIMEOUT: false,
	PAYLOAD_TOO_LARGE: false,
	VALIDATION_ERROR: false,
	INTERNAL_ERROR: false,
});

export const SUPPRESSABLE_ERROR_CODES: ReadonlySet<EmitoErrorCode> = new Set(
	(Object.entries(SUPPRESSABLE_RECORD) as [EmitoErrorCode, boolean][])
		.filter(([, v]) => v)
		.map(([k]) => k),
);

export interface EmitoErrorOptions {
	code: EmitoErrorCode;
	message: string;
	statusCode?: number;
	isRetryable?: boolean;
	context?: Record<string, unknown>;
	cause?: Error;
}

export class EmitoError extends Error {
	readonly code: EmitoErrorCode;
	readonly statusCode: number;
	readonly isRetryable: boolean;
	readonly context: Record<string, unknown>;

	constructor(options: EmitoErrorOptions) {
		super(options.message, { cause: options.cause });
		this.name = "EmitoError";
		this.code = options.code;
		this.statusCode = options.statusCode ?? ERROR_STATUS_CODES[options.code];
		this.isRetryable = options.isRetryable ?? RETRYABLE_CODES.has(options.code);
		this.context = options.context ?? {};

		Object.defineProperty(this, "code", { writable: false, configurable: false });
		Object.defineProperty(this, "statusCode", { writable: false, configurable: false });
		Object.defineProperty(this, "isRetryable", { writable: false, configurable: false });
		Object.defineProperty(this, "context", { writable: false, configurable: false });
	}

	static fromUnknown(
		err: unknown,
		defaults: Omit<EmitoErrorOptions, "message"> & { message?: string },
	): EmitoError {
		const cause = err instanceof Error ? err : undefined;
		const message = defaults.message ?? (cause?.message || "Unknown error");
		return new EmitoError({ ...defaults, message, cause });
	}
}

export { ERROR_STATUS_CODES };
